version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  producer:
    build: .
    container_name: producer
    command: npm run start
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
  worker:
    build: .
    container_name: worker
    command: npm run worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    deploy:
      replicas: 3 

